# Generated by Django 5.2 on 2025-04-21 20:02
# Este arquivo foi gerado automaticamente pelo Django quando você executou:
# python manage.py makemigrations
# Ele representa mudanças no banco de dados (criação de tabelas).
# Cada bloco dentro de "operations" cria um model como tabela SQL.

import django.db.models.deletion
from django.db import migrations, models

# Classe principal responsável por aplicar e desfazer esta migração.
class Migration(migrations.Migration):

    # Marca que esta é a primeira migração da aplicação (não depende de nenhuma anterior)
    initial = True

    # Lista de migrações das quais esta depende (vazia, pois é a inicial)
    dependencies = [
    ]

    # Conjunto de operações que serão aplicadas ao banco de dados.
    operations = [

        # ==============================
        # Modelo: Categoria
        # ==============================
        migrations.CreateModel(
            name='Categoria',   # Nome da tabela (core_categoria)
            fields=[
                # Campo ID padrão do Django, primary_key
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Nome da categoria – ex: "Urgente", "Infraestrutura"
                ('nome', models.CharField(max_length=100)),

                # Descrição textual da categoria
                ('descricao', models.TextField()),

                # Data de criação – gerada automaticamente
                ('criada_em', models.DateTimeField(auto_now_add=True)),

                # Indica se a categoria está ativa ou não
                ('ativa', models.BooleanField(default=True)),

                # Prioridade numérica (ex: 1 = mais urgente)
                ('prioridade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),

        # ==============================
        # Modelo: Equipe
        # ==============================
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Nome da equipe – ex: "Equipe de Desenvolvimento"
                ('nome', models.CharField(max_length=100)),

                # Responsável – ex: “João Silva”
                ('responsavel', models.CharField(max_length=100)),

                # Setor da empresa – ex: "TI", "Financeiro"
                ('setor', models.CharField(max_length=100)),

                # Define se essa equipe está ativa
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),

        # ==============================
        # Modelo: Membro
        # ==============================
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Nome da pessoa
                ('nome', models.CharField(max_length=100)),

                # E-mail para contato
                ('email', models.EmailField(max_length=254)),

                # Função dentro da equipe – ex: “Desenvolvedor”
                ('funcao', models.CharField(max_length=100)),

                # Data de entrada na equipe ou no projeto
                ('data_entrada', models.DateField()),

                # Relacionamento: muitos membros pertencem a uma única equipe
                ('equipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.equipe'
                )),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),

        # ==============================
        # Modelo: Projeto
        # ==============================
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Título do projeto – ex: “Sistema de Gestão”
                ('titulo', models.CharField(max_length=200)),

                # Descrição completa do projeto
                ('descricao', models.TextField()),

                # Data de início do projeto
                ('data_inicio', models.DateField()),

                # Data de conclusão prevista
                ('data_fim', models.DateField()),

                # Relação: um projeto pertence a uma categoria
                ('categoria', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.categoria'
                )),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),

        # Adiciona campo “projeto” ao modelo Equipe
        migrations.AddField(
            model_name='equipe',
            name='projeto',

            # OneToOneField: cada equipe está associada a **um único** projeto
            # e cada projeto só pode ter UMA equipe principal.
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.projeto'
            ),
        ),

        # ==============================
        # Modelo: Tarefa
        # ==============================
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Título da tarefa – ex: “Criar API”
                ('titulo', models.CharField(max_length=200)),

                # Status: ex: “Pendente”, “Em andamento”, “Concluída”
                ('status', models.CharField(max_length=50)),

                # Prazo final da tarefa
                ('prazo', models.DateField()),

                # Membro responsável (opcional)
                ('atribuida_para', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='core.membro'
                )),

                # A qual projeto pertence
                ('projeto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.projeto'
                )),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),

        # ==============================
        # Modelo: Comentario
        # ==============================
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Conteúdo textual do comentário
                ('conteudo', models.TextField()),

                # Data da criação
                ('criado_em', models.DateTimeField(auto_now_add=True)),

                # Indica se o comentário já foi editado após criado
                ('editado', models.BooleanField(default=False)),

                # Um comentário pode ter vários autores (caso raro, mas permitido)
                ('autores', models.ManyToManyField(to='core.membro')),

                # Todo comentário pertence a uma tarefa específica
                ('tarefa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.tarefa'
                )),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
