# Generated by Django 5.2 on 2025-04-22 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='comentarios/'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='importancia',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='equipe',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
