# Generated by Django 5.2 on 2025-04-22 02:38
# Esta migração adiciona novos campos aos modelos já existentes na aplicação “core”.
# Ela depende da migração 0001_initial (a que criou todas as tabelas originais).

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    # Esta migração depende da anterior (0001_initial)
    dependencies = [
        ('core', '0001_initial'),
    ]

    # Conjunto de operações que serão aplicadas ao banco de dados.
    operations = [

        # =======================================
        # Adiciona campo "anexo" ao modelo Comentario
        # =======================================
        migrations.AddField(
            model_name='comentario',
            name='anexo',

            # FileField permite upload de arquivos.
            # upload_to='comentarios/' → salva os arquivos na pasta MEDIA_ROOT/comentarios/
            # null=True → pode não ter valor no banco
            # blank=True → pode ser deixado vazio no formulário
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='comentarios/'
            ),
        ),

        # =======================================
        # Adiciona campo "importancia" ao modelo Comentario
        # =======================================
        migrations.AddField(
            model_name='comentario',
            name='importancia',

            # Campo texto simples que representa importância do comentário
            # Ex.: "normal", "urgente", "aviso", etc.
            # default='normal' → valor padrão
            field=models.CharField(
                default='normal',
                max_length=50
            ),
        ),

        # =======================================
        # Adiciona campo "criada_em" ao modelo Equipe
        # =======================================
        migrations.AddField(
            model_name='equipe',
            name='criada_em',

            # Data/hora automática de criação da equipe
            # auto_now_add=True → o valor é salvo automaticamente na criação
            # default=timezone.now → necessário para tabelas já existentes
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),

            # preserve_default=False → Django remove o default após criar a coluna
            preserve_default=False,
        ),

        # =======================================
        # Adiciona campo "telefone" ao modelo Membro
        # =======================================
        migrations.AddField(
            model_name='membro',
            name='telefone',

            # Telefone não é obrigatório
            # blank=True → pode ser deixado sem valor no formulário
            field=models.CharField(
                blank=True,
                max_length=20
            ),
        ),

        # =======================================
        # Adiciona campo "orcamento" ao modelo Projeto
        # =======================================
        migrations.AddField(
            model_name='projeto',
            name='orcamento',

            # DecimalField é ideal para valores financeiros
            # max_digits=10 → suporta números como 12345678.90
            # decimal_places=2 → duas casas decimais
            # default=0.0 → valor padrão para registros antigos
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                default=0.0
            ),
            preserve_default=False,
        ),

        # =======================================
        # Adiciona campo "descricao" ao modelo Tarefa
        # =======================================
        migrations.AddField(
            model_name='tarefa',
            name='descricao',

            # Campo de texto para detalhar tarefas
            # blank=True → não obrigatório
            field=models.TextField(
                blank=True
            ),
        ),
    ]
