# Generated by Django 5.2 on 2025-04-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario_anexo_comentario_importancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
