# Generated by Django 5.2 on 2025-04-22 03:05
# Esta migração adiciona um novo campo ao modelo Equipe.
# Ela dá continuidade às alterações feitas nas migrações anteriores.

from django.db import migrations, models


class Migration(migrations.Migration):

    # Esta migração depende da migração "0002",
    # que adicionou campos como anexo, importancia, telefone etc.
    dependencies = [
        ('core', '0002_comentario_anexo_comentario_importancia_and_more'),
    ]

    # Lista de operações a serem aplicadas no banco de dados
    operations = [

        # =======================================
        # Adiciona campo "observacoes" ao modelo Equipe
        # =======================================
        migrations.AddField(
            model_name='equipe',   # Modelo que receberá o campo
            name='observacoes',    # Nome do novo campo

            # TextField → usado para grandes quantidades de texto
            # blank=True → campo opcional no formulário
            field=models.TextField(blank=True),
        ),
    ]
