# Generated by Django 5.2 on 2025-04-22 03:08
# Esta migração adiciona um novo campo ao modelo Tarefa.
# Ela dá continuidade à evolução da aplicação, expandindo os atributos das tarefas.

from django.db import migrations, models


class Migration(migrations.Migration):

    # Esta migração depende da migração anterior (0003),
    # que adicionou o campo "observacoes" à Equipe.
    dependencies = [
        ('core', '0003_equipe_observacoes'),
    ]

    operations = [

        # =======================================
        # Adiciona campo "tipo" ao modelo Tarefa
        # =======================================
        migrations.AddField(
            model_name='tarefa',   # Modelo alvo da alteração
            name='tipo',           # Nome da nova coluna

            # CharField: ideal para textos curtos (categorias, tipos, rótulos)
            # max_length=50 → tamanho máximo
            # default='Geral' → registros antigos recebem esse valor automaticamente
            field=models.CharField(
                default='Geral',
                max_length=50
            ),
        ),
    ]
