# Generated by Django 5.2 on 2025-04-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipe_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(default='Geral', max_length=50),
        ),
    ]
